global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'pipeline-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd-exporter:9102']
  
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
  
  - job_name: 'airflow-webserver'
    static_configs:
      - targets: ['airflow-webserver:8080']
    metrics_path: '/admin/metrics'