mappings:
  # Airflow task metrics
  - match: "airflow.dag_processing.*"
    name: "airflow_dag_processing"
    labels:
      type: "$1"

  - match: "airflow.executor.*"
    name: "airflow_executor"
    labels:
      type: "$1"

  - match: "airflow.scheduler.*"
    name: "airflow_scheduler"
    labels:
      type: "$1"

  - match: "airflow.dagrun.*.*.duration"
    name: "airflow_dagrun_duration"
    labels:
      dag_id: "$1"
      run_id: "$2"

  - match: "airflow.task.*.*.*.duration"
    name: "airflow_task_duration"
    labels:
      dag_id: "$1"
      task_id: "$2"
      state: "$3"